inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - db/migrate/*
    - vendor/**/*
    - spec/**/*
    - config/**/*
    - test/**/*
    - app/controllers/users/registrations_controller.rb

  Rails:
    enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 20

AsciiComments:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
  
Style/RedundantSelf:
  Enabled: false
  
Style/RescueStandardError:
  Enabled: false
  
Style/SymbolArray:
  Enabled: false
  
Style/ClassAndModuleChildren:
  Enabled: false